11.0 website event waiting list translations
simahawk/odoo-event-addons pull request #1
Opened 2018-11-23 15:16 UTC by grindtildeath

2018-11-26 07:20 UTC, simahawk requested changes

2018-11-26 07:20 UTC, simahawk commented on website_event_waiting_list/i18n/fr.po
> +#~ msgid "&amp;times;"
this part can be trashed. "Register" is already translated

2018-11-29 15:22 UTC, grindtildeath commented
@simahawk updated.

2018-11-30 07:20 UTC, simahawk approved these changes

2018-11-30 07:20 UTC, merged